name: Run name
run-name: Run by @${{ github.actor }}
on: push
jobs:
    prints:
        name: Greeting
        runs-on: ubuntu-latest
        steps: 
            - name: Hello
              run: echo "Hello"